### ISSUE TITLE
Return undefined

### ISSUE THREAD

**Issue by RisedSky** [FlabbyBum/fortnite-publicapi#1]
![image](https://user-images.githubusercontent.com/23197999/52528032-77bb5c80-2cd3-11e9-9c6f-39933947922b.png)
![image](https://user-images.githubusercontent.com/23197999/52528033-7db13d80-2cd3-11e9-9aae-f7bc3360ac3c.png)

**Comment by FlabbyBum** [comment]
@RisedSky Fixed in latest version
